FROM golang
COPY . /go/src/github.com/kcmerrill/davni
# lazy, copying it in both places(for entrypoint.sh)
COPY . /code
WORKDIR /go/src/github.com/kcmerrill/davni
RUN go build -o /usr/local/bin/davni
ENTRYPOINT ["davni"]