version: "3.3"

services:
  golangservice:
    build:
      context: .
      dockerfile: Dockerfile.golang-service
    entrypoint: davni
    volumes:
      - /tmp/pdfs:/pdfs
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock