FROM golang
# lazy, copying it in both places
COPY . /go/src/github.com/kcmerrill/davni
COPY . /code
WORKDIR /go/src/github.com/kcmerrill/davni
RUN go build -o /usr/local/bin/davni
ENTRYPOINT ["davni"]